QuickFood/Areas/Admin/Controllers/FooderController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using QuickFood.Models.Business;
using QuickFood.Models.EF;

namespace QuickFood.Areas.Admin.Controllers
{
    public class FooderController : Controller
    {
        Order_Restaurant_Db db = new Order_Restaurant_Db();
        // GET: Admin/Fooder
        public ActionResult Index(long? Food_ID, int page = 1, int pagesize = 10)
        {
            var model = db.Foods.Where(x => x.Status == true).OrderByDescending(x => x.CreatedDate).ToPagedList(page, pagesize);
            var lstTopping = new List<Topping>();
            if(Food_ID != 0)
            {
                lstTopping = db.Toppings.Where(x => x.Food_ID == Food_ID).ToList();
            }
            else
            {
                lstTopping = db.Toppings.OrderByDescending(x => x.Food.CreatedDate).ToList();
            }

            ViewBag.LstTopping = lstTopping;
            return View(model);
        }



        // GET: Admin/Fooder/Create
        public ActionResult Create()
        {
            ViewBag.LstCategory = db.Food_Category.ToList();
            return View();
        }

        // POST: Admin/Fooder/Create
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Food entity, HttpPostedFileBase Image)
        {
            try
            {
                //Thêm hình ảnh
                var path = Path.Combine(Server.MapPath("~/Assets/Client/img/food"), Image.FileName);
                if (System.IO.File.Exists(path))
                {
                    string extensionName = Path.GetExtension(Image.FileName);
                    string filename = Image.FileName + DateTime.Now.ToString("ddMMyyyy") + extensionName;
                    path = Path.Combine(Server.MapPath("~/Assets/Client/img/food"), filename);
                    Image.SaveAs(path);
                    entity.Image = filename;
                }
                else
                {
                    Image.SaveAs(path);
                    entity.Image = Image.FileName;
                }

                entity.CreatedDate = DateTime.Now;
                entity.MetaTitle = Str_Metatitle(entity.Name);
                entity.Status = true;
                db.Foods.Add(entity);
                db.SaveChanges();
                TempData["message"] = "Thêm mới món ăn thành công!";
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["message"] = "Thêm món ăn KHÔNG thành công";
                return RedirectToAction("Index");
            }

        }

        // GET: Admin/Fooder/Edit/5
        public ActionResult Edit(int ID)
        {
            ViewBag.Food = new FoodBusiness().FindID(ID);
            ViewBag.LstCategory = db.Food_Category.ToList();
            return View();
        }

        // POST: Admin/Fooder/Edit/5
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(Food entity, HttpPostedFileBase Image)
        {
            var food = db.Foods.Find(entity.ID);

            try
            {
                if (Image != null && food.Image != Image.FileName)
                {
                    //Xóa file cũ
                    System.IO.File.Delete(Path.Combine(Server.MapPath("~/Assets/Client/img/food"), food.Image));
                    //Thêm hình ảnh
                    var path = Path.Combine(Server.MapPath("~/Assets/Client/img/food"), Image.FileName);
                    if (System.IO.File.Exists(path))
                    {
                        string extensionName = Path.GetExtension(Image.FileName);
                        string filename = Image.FileName + DateTime.Now.ToString("ddMMyyyy") + extensionName;
                        path = Path.Combine(Server.MapPath("~/Assets/Client/img/food"), filename);
                        Image.SaveAs(path);
                        food.Image = filename;
                    }
                    else
                    {
                        Image.SaveAs(path);
                        food.Image = Image.FileName;
                    }
                }

                food.Name = entity.Name;
                food.Price = entity.Price;
                food.Food_CategoryID = entity.Food_CategoryID;
                food.CreatedDate = DateTime.Now;
                food.MetaTitle = Str_Metatitle(entity.Name);

                db.SaveChanges();
                TempData["message"] = "Cập nhật món ăn thành công!";
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["message"] = "Cập nhật món ăn KHÔNG thành công!";
                return RedirectToAction("Index");
            }

        }



        // POST: Admin/Fooder/Delete/5
        [HttpPost]
        public JsonResult Delete(long ID)
        {
            var food = db.Foods.Find(ID);
            System.IO.File.Delete(Path.Combine(Server.MapPath("~/Assets/Client/img/food"), food.Image));

            var res = new FoodBusiness().DeleteFood(ID);
            if (res)
            {
                return Json(new { status = true });
            }
            else
            {
                return Json(new { status = false });
            }

        }

        [HttpPost]
        public ActionResult frmAdd_Topping(Topping entity, HttpPostedFileBase Image, int Page)
        {
            try
            {
                //Thêm hình ảnh
                var path = Path.Combine(Server.MapPath("~/Assets/Client/img/topping"), Image.FileName);
                if (System.IO.File.Exists(path))
                {
                    string extensionName = Path.GetExtension(Image.FileName);
                    string filename = Image.FileName + DateTime.Now.ToString("ddMMyyyy") + extensionName;
                    path = Path.Combine(Server.MapPath("~/Assets/Client/img/topping"), filename);
                    Image.SaveAs(path);
                    entity.Image = filename;
                }
                else
                {
                    Image.SaveAs(path);
                    entity.Image = Image.FileName;
                }

                db.Toppings.Add(entity);
                db.SaveChanges();
                TempData["message"] = "Thêm mới topping thành công!";
                return Redirect("/Admin/Fooder?Food_ID=" + entity.Food_ID + "&Page=" + Page);
            }
            catch
            {
                TempData["message"] = "Thêm topping KHÔNG thành công";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public ActionResult frmEdit_Topping(Topping entity, HttpPostedFileBase Image, int Page)
        {
            var topping = db.Toppings.Find(entity.ID);

            try
            {
                if (Image != null && Image.FileName != topping.Image)
                {
                    //Xóa file cũ
                    System.IO.File.Delete(Path.Combine(Server.MapPath("~/Assets/Client/img/topping"), topping.Image));
                    //Thêm hình ảnh
                    var path = Path.Combine(Server.MapPath("~/Assets/Client/img/topping"), Image.FileName);
                    if (System.IO.File.Exists(path))
                    {
                        string extensionName = Path.GetExtension(Image.FileName);
                        string filename = Image.FileName + DateTime.Now.ToString("ddMMyyyy") + extensionName;
                        path = Path.Combine(Server.MapPath("~/Assets/Client/img/topping"), filename);
                        Image.SaveAs(path);
                        topping.Image = filename;
                    }
                    else
                    {
                        Image.SaveAs(path);
                        topping.Image = Image.FileName;
                    }
                }

                topping.Name = entity.Name;
                topping.Price = entity.Price;

                db.SaveChanges();
                TempData["message"] = "Cập nhật topping thành công!";
                return Redirect("/Admin/Fooder?Food_ID=" + topping.Food_ID + "&Page=" + Page);
            }
            catch
            {
                TempData["message"] = "Cập nhật topping KHÔNG thành công!";
                return RedirectToAction("Index");
            }
        }

        public JsonResult DeleteTopping(long ID)
        {
            var topping = db.Toppings.Find(ID);
            System.IO.File.Delete(Path.Combine(Server.MapPath("~/Assets/Client/img/topping"), topping.Image));

            db.Toppings.Remove(topping);
            db.SaveChanges();
            return Json(new { status = true });
        }

        public JsonResult GetFoodById(long ID)
        {
            db.Configuration.ProxyCreationEnabled = false;
            var food = db.Foods.Find(ID);
            return Json(food, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetToppingById(long ID)
        {
            db.Configuration.ProxyCreationEnabled = false;
            var topping = db.Toppings.Find(ID);
            return Json(topping, JsonRequestBehavior.AllowGet);
        }

        public string Str_Metatitle(string str)
        {
            string[] VietNamChar = new string[]
            {
                "aAeEoOuUiIdDyY",
                "áàạảãâấầậẩẫăắằặẳẵ",
                "ÁÀẠẢÃÂẤẦẬẨẪĂẮẰẶẲẴ",
                "éèẹẻẽêếềệểễ",
                "ÉÈẸẺẼÊẾỀỆỂỄ",
                "óòọỏõôốồộổỗơớờợởỡ",
                "ÓÒỌỎÕÔỐỒỘỔỖƠỚỜỢỞỠ",
                "úùụủũưứừựửữ",
                "ÚÙỤỦŨƯỨỪỰỬỮ",
                "íìịỉĩ",
                "ÍÌỊỈĨ",
                "đ",
                "Đ",
                "ýỳỵỷỹ",
                "ÝỲỴỶỸ:/"
            };
            //Thay thế và lọc dấu từng char      
            for (int i = 1; i < VietNamChar.Length; i++)
            {

QuickFood/Areas/Admin/Views/Fooder/Create.cshtml
@using QuickFood.Models.EF

@{
    ViewBag.Title = "Thêm mới món ăn";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var lstCategory = ViewBag.LstCategory as List<Food_Category>;
}




<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header charecter-style">Thêm mới món ăn</h1>
    </div>
</div>
<div class="row">
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success text-center text-uppercase" id="AlertBox">
            @TempData["message"]
        </div>
    }
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">

            @using (Html.BeginForm("Create", "Fooder", FormMethod.Post, new { id = "frmValidate", enctype = "multipart/form-data" }))
            {
                <div class="panel-heading">
                    <h3 class="text-center">Thông tin món ăn</h3>
                </div>
                <div class="panel-body">
                    <div class="form-group col-md-6">
                        <label>Tên món ăn</label>
                        <input type="text" class="form-control" name="Name" placeholder="Nhập tên món ăn">
                    </div>
                    <div class="form-group col-md-6">
                        <label>Giá</label>
                        <input type="number" min="5000" class="form-control" name="Price" placeholder="Nhập giá bán món ăn">
                    </div>

                    <div class="form-group col-md-6">
                        <label>Danh mục món ăn</label>
                        <select name="Food_CategoryID" class="form-control">
                            <option value="">---Chọn danh mục---</option>
                            @foreach (var item in lstCategory)
                            {
                                <option value="@item.ID">@item.Name</option>
                            }
                        </select>
                    </div>

                    <div class="form-group col-md-6">
                        <label>Hình ảnh</label>
                        <label for="imgInp"  class="custom-file-upload">
                            <i class="fa fa-cloud-upload"></i>
                        </label>
                        <input name="Image" type="file" id="imgInp" accept="image/*"> <br>
                        <img id="blah" src="~/Assets/Client/img/empty.jpg" alt="your image" width="100px" />
                    </div>
                </div>

                <div class="panel-footer">
                    <div class="form-group text-center">
                        <button type="submit" class="btn btn-default btn-lg">Thêm mới</button>
                    </div>
                </div>
               
            }

        </div>
    </div>
</div>


@section jsFooter{

    <script>
        imgInp.onchange = evt => {
    		const [file] = imgInp.files
    		if (file) {
    			blah.src = URL.createObjectURL(file)
    		}
    	}
        $(document).ready(function () {

             $('#file-upload').change(function () {
                var i = $(this).prev('label').clone();
                var file = '<i class="fa fa-cloud-upload"></i>' + $('#file-upload')[0].files[0].name;
                $(this).prev('label').empty();
                $(this).prev('label').append(file);
            });

            $.validator.addMethod("select_validate", function (value, element, arg) {
                return arg !== value;
            }, "Value must not equal arg.");

            //Khi bàn phím được nhấn và thả ra thì sẽ chạy phương thức này
            $("#frmValidate").validate({
                rules: {
                    Name: "required",
                    Image: "required",
                    Price: "required",
                    Ingredient: "required",
                    Description: "required",
                    Food_CategoryID: { select_validate: "" }
                },
                messages: {
                    Name: "Vui lòng nhập tên món ăn",
                    Image: "Vui lòng chọn hình ảnh món ăn",
                    Price: "Vui lòng nhập giá món ăn",
                    Ingredient: "Vui lòng nhập thành phần món ăn",
                    Description: "Vui lòng nhập mô tả món ăn",
                    Food_CategoryID: { select_validate: "Bạn chưa chọn danh mục món ăn!" }
                }
            });
        });
    </script>

}

QuickFood/Areas/Admin/Views/Fooder/Edit.cshtml
@using QuickFood.Models.EF;

@{
    ViewBag.Title = "Cập nhật món ăn";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var food = ViewBag.Food as Food;
    var lstCategory = ViewBag.LstCategory as List<Food_Category>;
}


<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header charecter-style">Cập nhật thông tin món ăn</h1>
    </div>
</div>
<div class="row">
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success text-center text-uppercase" id="AlertBox">
            @TempData["message"]
        </div>
    }
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
            </div>
            <div class="panel-body">
                @using (Html.BeginForm("Edit", "Fooder", FormMethod.Post, new { id = "frmValidate", enctype = "multipart/form-data" }))
                {
                    <input type="hidden" name="ID" value="@food.ID" />
                    <div class="form-group col-md-6">
                        <label>Tên món ăn</label>
                        <input type="text" class="form-control" name="Name" value="@food.Name" placeholder="Nhập tên món ăn">
                    </div>

                    <div class="form-group col-md-6">
                        <label>Danh mục món ăn</label>
                        <select name="Food_CategoryID" class="form-control">
                            <option value="">---Chọn danh mục---</option>
                            @foreach (var item in lstCategory)
                            {
                                <option value="@item.ID" @(item.ID == food.Food_CategoryID ? "selected" : "")>@item.Name</option>
                            }
                        </select>
                    </div>
                    <div class="form-group col-md-6">
                        <label>Giá</label>
                        <input type="number" min="5000" class="form-control" name="Price" value="@food.Price" placeholder="Nhập giá bán món ăn">
                    </div>
                    <div class="form-group col-md-6">
                        <label>Hình ảnh</label>
                        <label for="imgInp"  class="custom-file-upload">
                            <i class="fa fa-cloud-upload"></i>
                        </label>
                        <input name="Image" type="file" id="imgInp" accept="image/*" style="display:none;"> <br>
                        <img id="blah" src="~/Assets/Client/img/food/@food.Image" alt="your image" width="100px" />
                    </div>


                    <div class="form-group text-center">
                        <button type="submit" class="btn btn-default btn-lg">Cập nhật</button>
                    </div>
                }

            </div>
        </div>
    </div>
</div>


@section jsFooter{

    <script type="text/javascript">

        imgInp.onchange = evt => {
    		const [file] = imgInp.files
    		if (file) {
    			blah.src = URL.createObjectURL(file)
    		}
    	}
        $(document).ready(function () {

            $('#file-upload').change(function () {
                var i = $(this).prev('label').clone();
                var file = '<i class="fa fa-cloud-upload"></i>' + $('#file-upload')[0].files[0].name;
                $(this).prev('label').empty();
                $(this).prev('label').append(file);
            });
            $.validator.addMethod("select_validate", function (value, element, arg) {
                return arg !== value;
            }, "Value must not equal arg.");

            //Khi bàn phím được nhấn và thả ra thì sẽ chạy phương thức này
            $("#frmValidate").validate({
                rules: {
                    Name: "required",
                    Image: "required",
                    Price: "required",
                    Ingredient: "required",
                    Description: "required",
                    Food_CategoryID: { select_validate: "" }
                },
                messages: {
                    Name: "Vui lòng nhập tên món ăn",
                    Image: "Vui lòng chọn hình ảnh món ăn",
                    Price: "Vui lòng nhập giá món ăn",
                    Ingredient: "Vui lòng nhập thành phần món ăn",
                    Description: "Vui lòng nhập mô tả món ăn",
                    Food_CategoryID: { select_validate: "Bạn chưa chọn danh mục món ăn!" }
                }
            });
        });
    </script>

}